# Generated by Django 5.2.12 on 2026-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_description',
            field=models.TextField(blank=True, help_text='Provide details if selecting Custom Service', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('oil_change', 'Oil Change'), ('tyre_replacement', 'Tyre Replacement'), ('brake_inspection', 'Brake Inspection'), ('general_checkup', 'General Checkup'), ('engine_tuneup', 'Engine Tune-up'), ('ac_service', 'AC Service & Repair'), ('suspension_repair', 'Suspension Repair'), ('battery_replacement', 'Battery Replacement'), ('custom', 'Custom Service (Write query)')], max_length=50),
        ),
    ]
