# Generated by Django 5.2.12 on 2026-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_custom_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Approximate date of last service', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('suv', 'SUV')], default='car', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Current Odometer Reading', null=True),
        ),
    ]
